CK)
    # eraser_text = font.render("E", True, BLACK)
    # decrease_text = font.render("-", True, BLACK)
    # increase_text = font.render("+", True, BLACK)
    # clear_text = font.render("C", True, BLACK)